name: 增强博客自动化

on:
  schedule:
    # 每天下午1点 (韩国时间) - 每天只运行一次
    - cron: '0 4 * * *'   # 下午1:00 KST = UTC 04:00
  workflow_dispatch: # 手动运行
    inputs:
      topic:
        description: '博客文章主题 (可选)'
        required: false
        type: string
      labels:
        description: '文章标签 (逗号分隔)'
        required: false
        type: string
        default: 'AI,博客'

permissions:
  contents: write

jobs:
  auto-blog-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码库
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 缓存Python包
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-oauthlib google-generativeai
        
    - name: 创建配置文件
      run: |
        cat > config.ini << EOF
        [GOOGLE]
        client_id = ${{ secrets.GOOGLE_CLIENT_ID }}
        client_secret = ${{ secrets.GOOGLE_CLIENT_SECRET }}
        blog_id = ${{ secrets.BLOGGER_BLOG_ID }}
        scopes = https://www.googleapis.com/auth/blogger
        
        [AI]
        gemini_api_key = ${{ secrets.GEMINI_API_KEY }}
        model = gemini-pro
        max_tokens = 2000
        
        [CONTENT]
        default_labels = AI,博客,GitHub
        post_format = html
        language = zh
        
        [AUTOMATION]
        topics_file = topics.json
        post_history = post_history.json
        max_posts_per_day = 3
        EOF
        
    - name: 从密钥创建令牌文件
      run: |
        echo '${{ secrets.BLOGGER_TOKEN_JSON }}' > blogger_token.json
        
    - name: 运行自动化博客发布
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
      run: |
        if [[ -n "${{ github.event.inputs.topic }}" ]]; then
          python enhanced_blog_automation.py --topic "${{ github.event.inputs.topic }}" --labels "${{ github.event.inputs.labels }}"
        else
          python enhanced_blog_automation.py --auto
        fi
        
    - name: 上传日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: 博客自动化日志
        path: |
          blog_automation.log
          post_history.json
        retention-days: 30
        
    - name: 提交更新的历史记录
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [[ -f post_history.json ]]; then
          git add post_history.json
          git diff --staged --quiet || git commit -m "更新发布历史 - $(date +'%Y-%m-%d %H:%M')"
          git push
        fi

  notify-status:
    needs: auto-blog-post
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: 通知成功
      if: needs.auto-blog-post.result == 'success'
      run: |
        echo "✅ 博客自动化成功完成"
        echo "请检查您的博客查看新文章!"
        
    - name: 通知失败
      if: needs.auto-blog-post.result == 'failure'
      run: |
        echo "❌ 博客自动化失败"
        echo "请检查日志获取详细信息"
